name: Build Plugins

on: push

jobs:
  build:
    if: ${{ github.repository != 'Artemis-RGB/Artemis.PluginTemplate' && '[ -f .template ]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src

      # You'll need to fill in the name of your plugin here
      - name: Upload Artemis.Plugins.Devices.VialRGB
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.Devices.VialRGB
          path: src/Artemis.Plugins.Devices.VialRGB/bin/x64/Release/net7.0/publish

      - name: Upload Artemis.Plugins.VialRGB
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.VialRGB
          path: src/Artemis.Plugins.VialRGB/bin/x64/Release/net7.0/publish
